// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 12.0.0.0
//  
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Wcf
{
    using System.Linq;
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DomainTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
 
	string className = TableMeta.Name + "Domain";
	FilePath = TableMeta.NameSpace + ".Domain/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using System;\r\n\r\n\r\nnamespace ");
            
            #line 11 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain \r\n{\r\n\t/// <summary>");
            
            #line 13 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic class ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>");
            
            #line 18 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t\tpublic ");
            
            #line 19 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 19 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\t\t");
            
            #line 20 "D:\Jax-Work\Dropbox\JW-Project\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
