// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Wcf
{
    using System.Linq;
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class IDaoTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
 
	string className = "I" + TableMeta.Name + "Dao";
	FilePath = TableMeta.NameSpace + ".Dao/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.API.Models;\r\nusing ");
            
            #line 9 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 10 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\nusing System.Collections.Generic;\r\n\r\n\r\nnamespace ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao\r\n{\r\n\t/// <summary>");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic interface ");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t//TODO 程式產生未完成\r\n\t\t//Dictionary<int, string> GetDic(string status = null);" +
                    "\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//Dictionary<string, string> GetStatusItems();\r\n\r\n\t\tPagi" +
                    "nation<");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetPagination(WhereParams<");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Sort?> pageParams);\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//List<");
            
            #line 28 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetList(WhereParams<");
            
            #line 28 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam = null);\r\n\t\t\r\n\t\t");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain GetById(");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\tint Save(");
            
            #line 32 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain);\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
