// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Wcf
{
    using System.Linq;
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class IServiceTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
 
	string className = "I" + TableMeta.Name + "Service";
	FilePath = TableMeta.NameSpace + ".Service/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.API.Models;\r\nusing System.Collections.Generic;\r\nusing System.Servic" +
                    "eModel;\r\nusing ");
            
            #line 11 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 12 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\n\r\n\r\nnamespace ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service\r\n{\r\n\t/// <summary>");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t[ServiceContract]\r\n\tpublic interface ");
            
            #line 19 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t//TODO 程式產生未完成\r\n\t\t//[OperationContract]\r\n\t\t//Dictionary<int, string> GetD" +
                    "ic(string status);\r\n\t\t\r\n\t\t//TODO 程式產生未完成\r\n\t\t//[OperationContract]\r\n\t\t//Dictionar" +
                    "y<string, string> GetStatusItems();\r\n\r\n\t\t[OperationContract]\r\n\t\tPagination<");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetPagination(WhereParams<");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 30 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Sort?> pageParams);\r\n\t\t\r\n\t\t//TODO 程式產生未完成\r\n\t\t//[OperationContract]\r\n\t\t//List<");
            
            #line 34 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetList(WhereParams<");
            
            #line 34 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam);\r\n\r\n\t\t[OperationContract]\r\n\t\t");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain GetById(");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t[OperationContract]\r\n\t\tint Save(");
            
            #line 40 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\IServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain);\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
