// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Wcf
{
    using System.Linq;
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ServiceTestTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
 
	string className = TableMeta.Name + "ServiceTests";
	FilePath = TableMeta.NameSpace + ".Service.Impl.Tests/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.API;\r\nusing Moq;\r\nusing System;\r\nusing System.Collections.Generic;\r\nu" +
                    "sing System.Linq;\r\nusing System.Text;\r\nusing System.Threading.Tasks;\r\nusing ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao;\r\nusing ");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\nusing Xunit;\r\n\r\nnamespace ");
            
            #line 20 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service.Impl.Tests\r\n{\r\n\tpublic class ");
            
            #line 22 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\r\n\t\tpublic static IEnumerable<object[]> Save_ValidationTest_Data()\r\n\t\t{\r\n\t\t" +
                    "\tyield return new object[] { new ");
            
            #line 27 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain {\r\n\t\t\t//TODO 程式產生未完成\r\n\t\t\t}};\r\n\t\t}\r\n\r\n\r\n\t\t[Theory]\r\n\t\t[MemberData(\"Save_Val" +
                    "idationTest_Data\")]\r\n\t\tpublic void Save_ValidationTest(");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain)\r\n\t\t{\r\n\t\t\tvar mock = new Mock<I");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Dao>();\r\n\t\t\tvar ");
            
            #line 38 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service = new ");
            
            #line 38 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Service(mock.Object);\r\n\t\t\tAssert.Throws<OrionException>(() => ");
            
            #line 39 "D:\Jax-Work\Dropbox\JW-Project\NugetProject\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.Save(domain));\r\n\t\t}\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
