// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Wcf
{
    using System.Linq;
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ServiceTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
 
	string className = TableMeta.Name + "Service";
	FilePath = TableMeta.NameSpace + ".Service.Impl/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.API;\r\nusing Orion.API.Models;\r\nusing System;\r\nusing System.Linq;\r" +
                    "\nusing System.Collections.Generic;\r\nusing ");
            
            #line 13 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao;\r\nusing ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\n\r\n\r\nnamespace ");
            
            #line 18 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service.Impl\r\n{\r\n\t/// <summary>");
            
            #line 20 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic class ");
            
            #line 21 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 21 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate I");
            
            #line 23 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Dao _");
            
            #line 23 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao;\r\n\r\n\t\tpublic ");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(I");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Dao ");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao)\r\n\t\t{\r\n\t\t\t_");
            
            #line 27 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao = ");
            
            #line 27 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao;\r\n\t\t}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public Dictionary<int, string> GetDic(string" +
                    " status)\r\n\t\t//{\r\n\t\t//    return _");
            
            #line 34 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.GetDic(status);\r\n\t\t//}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public Dictionary<string, s" +
                    "tring> GetStatusItems()\r\n\t\t//{\r\n\t\t//    return _");
            
            #line 41 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.GetStatusItems();\r\n\t\t//}\r\n\r\n\r\n\t\tpublic Pagination<");
            
            #line 45 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetPagination(WhereParams<");
            
            #line 45 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 45 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Sort?> pageParams)\r\n\t\t{\r\n\t\t\treturn _");
            
            #line 47 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.GetPagination(findParam, pageParams);\r\n\t\t}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public " +
                    "List<");
            
            #line 52 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetList(WhereParams<");
            
            #line 52 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam)\r\n\t\t//{\r\n\t\t//    return _");
            
            #line 54 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.GetList(findParam);\r\n\t\t//}\r\n\r\n\r\n\t\tpublic ");
            
            #line 58 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain GetById(");
            
            #line 58 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 58 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar domain = _");
            
            #line 60 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.GetById(");
            
            #line 60 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tChecker.Has(domain, \"");
            
            #line 61 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("資料不存在\");\r\n\r\n\t\t\treturn domain;\r\n\t\t}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\tpublic int Save(");
            
            #line 68 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain)\r\n\t\t{\r\n");
            
            #line 70 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
 foreach(var col in TableMeta.Columns.Where(x => x.CodeType != "bool")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t\tChecker.Has(domain.");
            
            #line 71 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 71 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Description));
            
            #line default
            #line hidden
            this.Write("不可以為空\");\r\n");
            
            #line 72 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\treturn _");
            
            #line 74 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Wcf\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Dao.Save(domain);\r\n\t\t}\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
