// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Mvc
{
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ControllersTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
 
	string className = TableMeta.Name + "Controller";
	FilePath = TableMeta.NameSpace + ".WebApp/Controllers/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.API;\r\nusing Orion.API.Extensions;\r\nusing Orion.API.Models;\r\nusi" +
                    "ng Orion.Mvc.Attributes;\r\nusing Orion.Mvc.Security;\r\nusing Orion.Mvc.Exten" +
                    "sions;\r\n\r\nusing ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\nusing ");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".WebApp.Models;\r\nusing ");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service;\r\nusing System.Collections.Generic;\r\nusing System.Web.Mvc;\r\nusing System" +
                    ".Web;\r\nusing System;\r\n\r\n\r\n\r\nnamespace ");
            
            #line 25 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".WebApp.Controllers \r\n{\r\n\t/// <summary>");
            
            #line 27 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t//XXX [ActAuthorize(ACT.");
            
            #line 28 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("View)]\r\n\tpublic class ");
            
            #line 29 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : Controller \r\n\t{\r\n\t\tprivate I");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service;\r\n\r\n\t\tprivate int _userId = -1;\r\n\r\n\r\n\t\tpublic ");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(I");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service)\r\n\t\t{\r\n\t\t\t_");
            
            #line 38 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 38 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write(@"Service;

		}

		
		protected override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			_userId = User.Identity.GetUserId();
		}

		protected override void OnActionExecuted(ActionExecutedContext filterContext)
		{
		}




		private ");
            
            #line 55 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain toDomain(");
            
            #line 55 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm)\r\n\t\t{\r\n\t\t\tif(vm  == null) { return null; }\r\n\r\n\t\t\tvar domain = new ");
            
            #line 59 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain \r\n\t\t\t{\r\n");
            
            #line 61 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 62 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = vm.");
            
            #line 62 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 63 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t};\t\t\t\r\n\t\t\tdomain.ModifyBy = _userId;\r\n\r\n\t\t\treturn domain;\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\t\tpubl" +
                    "ic ActionResult Index()\r\n\t\t{\r\n\t\t\treturn RedirectToAction(nameof(List));\r\n\t\t}\r\n\r\n" +
                    "\r\n\r\n\r\n\r\n\t\tpublic ActionResult List(WhereParams<");
            
            #line 82 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 82 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Sort?> pageParams)\r\n\t\t{\r\n\t\t\tPagination<");
            
            #line 84 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> domainPage = _");
            
            #line 84 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.GetPagination(findParam, pageParams);\r\n\t\t\tViewBag.Pagination = domainPage" +
                    ";\r\n\r\n\t\t\treturn View();\r\n\t\t}\r\n\r\n\r\n\r\n\t\tpublic ActionResult Export(WhereParams<");
            
            #line 92 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam)\r\n\t\t{\r\n\t\t\tPagination<");
            
            #line 94 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> domainPage = _");
            
            #line 94 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.GetPagination(findParam, null);\r\n\t\t\tViewBag.Pagination = domainPage;\r\n\r\n\t" +
                    "\t\treturn this.ExcelView($\"");
            
            #line 97 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("-{DateTime.Now:yyyyMMddHHmmss}.xls\");\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\t\t[HttpGet]\r\n\t\t[UseViewPage(\"" +
                    "Form\")]\r\n\t\t//XXX [ActAuthorize(ACT.");
            
            #line 105 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit)]\r\n\t\tpublic ActionResult Create()\r\n\t\t{\r\n\t\t\tvar vm = new ");
            
            #line 108 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\t\t\t{\r\n\t\t\t\t//TODO\r\n\t\t\t};\r\n\r\n\t\t\treturn View(vm);\r\n\t\t}\r\n\r\n\r\n\t\t[HttpPost]\r" +
                    "\n\t\t[UseViewPage(\"Form\")]\r\n\t\t//XXX [ActAuthorize(ACT.");
            
            #line 119 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit)]\r\n\t\tpublic ActionResult Create(");
            
            #line 120 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm)\r\n\t\t{\r\n\t\t\tif (!ModelState.IsValid) { return View(vm); }\r\n\r\n\t\t\tvar do" +
                    "main = toDomain(vm);\r\n\t\t\t");
            
            #line 125 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 125 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" = _");
            
            #line 125 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.Save(domain);\r\n\t\t\tthis.SetStatusSuccess(\"儲存成功!!\");\r\n\t\t\treturn RedirectToA" +
                    "ction(nameof(Edit), new { ");
            
            #line 127 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" });\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\r\n\r\n\t\t[HttpGet]\r\n\t\t[UseViewPage(\"Form\")]\r\n\t\tpublic ActionResul" +
                    "t Edit(");
            
            #line 137 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t");
            
            #line 139 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = _");
            
            #line 139 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.GetById(");
            
            #line 139 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t\tvar vm = new ");
            
            #line 141 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel \r\n\t\t\t{\r\n");
            
            #line 143 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 144 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.");
            
            #line 144 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 145 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t};\t\t\r\n\r\n\t\t\treturn View(vm);\r\n\t\t}\r\n\r\n\t\t[HttpPost]\r\n\t\t[UseViewPage(\"Form\")]\r\n\t\t/" +
                    "/XXX [ActAuthorize(ACT.");
            
            #line 153 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit)]\r\n\t\tpublic ActionResult Edit(");
            
            #line 154 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm)\r\n\t\t{\r\n\t\t\tif (!ModelState.IsValid) { return View(vm); }\r\n\r\n\t\t\tvar do" +
                    "main = toDomain(vm);\r\n\t\t\t");
            
            #line 159 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 159 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" = _");
            
            #line 159 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.Save(domain);            \r\n\t\t\tthis.SetStatusSuccess(\"儲存成功!!\");\r\n\t\t\treturn" +
                    " RedirectToAction(nameof(Edit), new { ");
            
            #line 161 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" });\r\n\t\t}\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
