// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Mvc
{
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DialogViewTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
 
	FilePath = TableMeta.NameSpace + ".WebApp/Views/" + TableMeta.Name + "/Dialog.cshtml";

            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 6 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\r\n\r\n@{\r\n\tLayout = \"~/Views/shared/_DialogLayout.cshtml\";\r\n\r\n\tbool isCr" +
                    "eate = Model.");
            
            #line 12 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" == 0;\r\n\t\r\n\tViewBag.Title = isCreate ? \"新增");
            
            #line 14 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("\" : \"編輯");
            
            #line 14 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write(@""";
}

@section Styles {
}


@section Scripts {
	<script type=""text/javascript"">
		Dialog.resize(700, 500);
	</script>
}

@if (TempData.ContainsKey(""StatusSuccess""))
{
	<script type=""text/javascript"">Dialog.close(200);</script> 
}


@using (Html.BeginForm(null, null, FormMethod.Post, new
{
	action = """",
	@class = ""form-horizontal form-sm"",
	ext_one_submit = """",
	ext_exit_alert = ""資料尚未儲存，確定要離開？"",
}))
{
	@Html.HiddenFor(m => m.");
            
            #line 41 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\r\n\t<div class=\"modal-header\">\r\n\t\t<h4 class=\"modal-title\">@ViewBag.Title</h4>\r" +
                    "\n\t</div>\r\n\r\n\t<div class=\"modal-body auto\">\r\n");
            
            #line 48 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t<div class=\"form-group col-xs-6\">\r\n\t\t\t@Html.BsLabelFor(m => m.");
            
            #line 50 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", new { @class = \"col-xs-4\" })\r\n\t\t\t<div class=\"col-xs-8\">\r\n\t\t\t\t@Html.BsTextBoxFor" +
                    "(m => m.");
            
            #line 52 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t<span class=\"form-tip\">@Html.ValidationMessageFor(m => m.");
            
            #line 53 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</span>\r\n\t\t\t</div>\r\n\t\t</div>\r\n");
            
            #line 56 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\DialogViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</div>\r\n\r\n\t<div class=\"modal-footer\">\r\n\t\t<span class=\"btn btn-default\" data-dism" +
                    "iss=\"modal\"><i class=\"fa fa-times fa-lg\"></i> 關閉</span>\r\n\t\t<button type=\"submit\"" +
                    " class=\"btn btn-primary\"><i class=\"fa fa-save fa-lg\"></i> 儲存</button>\r\n\t</div>\r\n" +
                    "}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
