// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Mvc
{
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class FormViewTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
 
	FilePath = TableMeta.NameSpace + ".WebApp/Views/" + TableMeta.Name + "/Form.cshtml";

            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 6 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\r\n\r\n@{\r\n\tbool isCreate = Model.");
            
            #line 10 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" == 0;\r\n\r\n\tViewBag.Title = isCreate ? \"新增");
            
            #line 12 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("\" : \"編輯");
            
            #line 12 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write(@""";
}

@section Styles {
}


@section Scripts {
}



<div class=""page-header"">
	<h1>@ViewBag.Title</h1>
</div>



@using (Html.BeginForm(null, null, FormMethod.Post, new
{
	action = """",
	@class = ""form-horizontal form-sm"",
	ext_one_submit = """",
	ext_exit_alert = ""資料尚未儲存，確定要離開？"",
}))
{
	@Html.HiddenFor(m => m.");
            
            #line 38 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(@")

	<div class=""well btn-toolbar hidden-print"" ext-scroll-follow="""">
		<div class=""toolbar-left"">
			<a class=""btn btn-default btn-sm"" href=""List""><i class=""fa fa-reply fa-lg""></i> 返回</a>
			<button type=""submit"" class=""btn btn-primary btn-sm""><i class=""fa fa-save fa-lg""></i> 儲存</button>
		</div>
	</div>

	<div class=""panel panel-default"">
		<div class=""panel-body row"">

");
            
            #line 50 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<div class=\"form-group col-xs-6\">\r\n\t\t\t\t@Html.BsLabelFor(m => m.");
            
            #line 52 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", new { @class = \"col-sm-4\" })\r\n\t\t\t\t<div class=\"col-sm-8\">\r\n\t\t\t\t\t@Html.BsTextBoxF" +
                    "or(m => m.");
            
            #line 54 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t<span class=\"form-tip\">@Html.ValidationMessageFor(m => m.");
            
            #line 55 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</span>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n");
            
            #line 58 "D:\Source\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\FormViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t</div>\r\n\r\n\t</div>\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
