// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 14.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerateByDatabase.Templates.Mvc
{
    using CodeGenerateByDatabase.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ListViewTemplate : CodeGenerateByDatabase.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 
	FilePath = TableMeta.NameSpace + ".WebApp/Views/" + TableMeta.Name + "/List.cshtml";

            
            #line default
            #line hidden
            this.Write("@{\r\n\tViewBag.Title = \"");
            
            #line 7 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("列表\";\r\n\r\n\t//Dictionary<int, string> userNameItems = ViewBag.UserNameItems; \r\n\tPagi" +
                    "nation<");
            
            #line 10 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(@"Domain> pagination = ViewBag.Pagination;

}

@section Styles {
}


@section Scripts {
}


<div class=""page-header"">
	<h1>@ViewBag.Title</h1>
</div>


@using (Html.BeginForm(null, null, FormMethod.Get, new { id = ""SearchForm"", @class = ""well btn-toolbar"" }))
{
	<div class=""toolbar-left"">
		<a class=""btn btn-success btn-sm"" href=""@Url.Action(""Create"")""><i class=""fa fa-plus fa-lg""></i> 新增</a>
	</div>

	<div class=""toolbar-left"">
		<select class=""where-builder hidden"">
");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<option value=\"");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\" type=\"");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CodeType.TrimEnd('?')));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 36 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Description));
            
            #line default
            #line hidden
            this.Write("</option>\r\n");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"		</select>
	</div>

	<div class=""toolbar-left"">
		<button type=""submit"" class=""btn btn-primary btn-sm""><i class=""fa fa-search fa-lg""></i> 搜尋</button>
	</div>
	
	<div class=""toolbar-left dropdown hidden-xs hidden-sm"">
		<span class=""btn btn-default btn-sm dropdown-toggle"" data-toggle=""dropdown"" title=""選擇欄位順序&amp;顯示"">
			<i class=""fa fa-eye-slash fa-lg""></i>
		</span>
		<ul class=""dropdown-menu fix-height"" ext-orderable-selector=""#");
            
            #line 49 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("List\"></ul>\r\n\t</div>\r\n\r\n\t@Html.Partial(\"_PageSizeChange\", pagination.TotalItems)\r" +
                    "\n}\r\n\r\n\r\n\r\n<div id=\"");
            
            #line 57 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("List\" class=\"table-responsive\">\r\n\t<table class=\"table table-striped table-bordere" +
                    "d table-nowrap table-hover\">\r\n\t\t<thead>\r\n\t\t\t<tr class=\"head\">\r\n\t\t\t\t<th class=\"mi" +
                    "n\"></th>\r\n");
            
            #line 62 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<th ext-orderable-col=\"\" class=\"");
            
            #line 63 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\">@Html.PagerSort(");
            
            #line 63 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Sort.");
            
            #line 63 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</th>\r\n");
            
            #line 64 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</thead>\r\n\t\t<tbody dialog-change-reload=\"\">\r\n\t\t\t@foreach (var row in " +
                    "pagination.List)\r\n\t\t\t{\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"min\">\r\n\t\t\t\t\t\t@{ string editUrl" +
                    " = Url.Action(\"Edit\", new { row.");
            
            #line 72 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" }); }\r\n\t\t\t\t\t\t<a class=\"btn btn-warning btn-sm btn-icon\" href=\"@editUrl\"><i class" +
                    "=\"fa fa-pencil fa-lg\"></i></a>\r\n\t\t\t\t\t</td>\r\n");
            
            #line 75 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td class=\"");
            
            #line 76 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\">@row.");
            
            #line 76 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n");
            
            #line 77 "D:\Jax-Work\Dropbox\JW-Project\RDSystems\CodeGenerateByDatabase\CodeGenerateByDatabase\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"				</tr>
			}
		</tbody>
	</table>

	<div class=""col-xs-12"" dialog-change-reload="""">
		<div class=""alert alert-danger well-sm @(pagination.TotalItems > 0 ? ""hide"" : """")""><b>[ 查無任何資料 ]</b></div>
	</div>
</div>


<div class=""text-center"">
	<ul class=""pagination"">@Html.PagerLinks(pagination)</ul>
</div>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
